name 'TrimGalore'
maintainer 'The Authors'
maintainer_email 'chef@eaglegenomics.com'
license 'all_rights'
description 'Installs/Configures TrimGalore'
long_description 'Installs/Configures TrimGalore'
version '0.1.0'

depends 'build-essential'
depends 'magic_shell'
depends 'FastQC'
depends 'cutadapt'
