name 'TrimGalore'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures templateCookbook'
long_description 'Installs/Configures templateCookbook'
version '0.1.0'

depends 'build-essential'
depends 'magic_shell'
